# Generated by Django 4.0.4 on 2022-05-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_created_at_book_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
