# Generated by Django 4.0.4 on 2022-07-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0005_remove_book_author_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(to='comments.comment'),
        ),
    ]
